name: PR Title Validation

on:
    pull_request:
        types:
            - opened
            - edited
            - review_requested
            - synchronize
            - reopened
        branches:
            - "**"

jobs:
    should-not-change-jira-no:
        runs-on: ubuntu-latest
        steps:
            - name: setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
