name: PR Validation

on:
    pull_request:
        branches:
            - "**"

jobs:
    on-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v2 # checkout the repository content to github runner.
            - name: setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: print env
              run: | 
                current_title=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
                old_title=$(jq --raw-output .changes.title.from "$GITHUB_EVENT_PATH")
                echo $current_title
                echo $old_title
                # if title's 1st part not matched, then raise an error
                python -m pip install requests
                python -m pip install PyGithub
                python -m pip install jira
                chmod 755 .github/pr_validation.py
                python ./.github/pr_validation.py  $current_title $old_title
              env:
                PROJECT_NAMES: TRANS;SPM;
